### ISSUE TITLE
Bugs with takePicture

### ISSUE THREAD

**Issue by Lyfei** [BluePerformance/capacitor-barcode-scanner#1]
see 

<img width="546" alt="takePicture" src="https://user-images.githubusercontent.com/18715528/216491906-8fe2d877-e20b-4bc4-b2d6-1cb94f46958d.png">

**Comment by fabus961** [comment]
Hi Lyfei,
thanks for your issue report. 
This one is pretty straightforward and will be fixed asap!

**Comment by Marco-Hochmuth** [comment]
Hi Lyfei,

Thanks for your issue. We've removed the call to the Log() function.

The android side of this package is currently the same as the original https://www.npmjs.com/package/@capacitor-community/barcode-scanner

We will only be able to implement the Android components in a few weeks or months and recommend using the original package until then.
